import postgres from "postgres";
import { config } from "dotenv";

config();

if (!process.env.DATABASE_URL) {
  console.error("❌ DATABASE_URL is not defined in .env file");
  process.exit(1);
}

const sql = postgres(process.env.DATABASE_URL);

const restaurants = [
  // 1. KOREAN (7 restaurants)
  {
    name: "명동 교자",
    nameEn: "Myeongdong Kyoja",
    nameZhTw: "明洞餃子",
    nameZhCn: "明洞饺子",
    category: "korean",
    address: "서울시 중구 명동 10길 29",
    addressEn: "29, Myeongdong 10-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區明洞10街29",
    addressZhCn: "首尔特别市中区明洞10街29",
    phone: "02-776-5348",
    rating: 48,
    reviewCount: 3842,
    price: "moderate",
    hours: "10:30 - 21:00",
    description: "1966년부터 이어온 전통의 칼국수와 만두 전문점. 미쉐린 가이드 빕 구르망 선정.",
    descriptionEn: "Traditional noodle and dumpling restaurant operating since 1966. Selected for Michelin Bib Gourmand.",
    descriptionZhTw: "始於1966年的傳統刀削麵和餃子專賣店。入選米其林必比登推薦。",
    descriptionZhCn: "始于1966年的传统刀削面和饺子专卖店。入选米其林必比登推荐。",
    image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=800",
    latitude: "37.5636",
    longitude: "126.9850",
    menuItems: [
      { name: "칼국수", nameEn: "Kalguksu (Chopped Noodles)", nameZhTw: "刀削麵", nameZhCn: "刀削面", price: 10000, description: "진한 닭 육수의 칼국수" },
      { name: "만두", nameEn: "Mandu (Dumplings)", nameZhTw: "餃子", nameZhCn: "饺子", price: 12000, description: "속이 꽉 찬 육즙 만두" },
      { name: "비빔국수", nameEn: "Bibim Guksu (Spicy Noodles)", nameZhTw: "拌麵", nameZhCn: "拌面", price: 10000, description: "매콤한 비빔국수" },
    ]
  },
  {
    name: "우래옥",
    nameEn: "Woo Lae Oak",
    nameZhTw: "又來屋",
    nameZhCn: "又来屋",
    category: "korean",
    address: "서울시 중구 창경궁로 62-29",
    addressEn: "62-29, Changgyeonggung-ro, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區昌慶宮路62-29",
    addressZhCn: "首尔特别市中区昌庆宫路62-29",
    phone: "02-2265-0151",
    rating: 47,
    reviewCount: 2150,
    price: "expensive",
    hours: "11:30 - 21:30",
    description: "서울 최고의 평양냉면을 맛볼 수 있는 곳. 깊은 육향이 특징입니다.",
    descriptionEn: "A place to taste the best Pyeongyang Naengmyeon in Seoul. Characterized by deep meat broth flavor.",
    descriptionZhTw: "可以品嚐到首爾最棒的平壤冷麵的地方。以濃郁的肉湯味為特徵。",
    descriptionZhCn: "可以品尝到首尔最棒的平壤冷面,以浓郁的肉汤味为特征。",
    image: "https://images.unsplash.com/photo-1596796929656-5b3287340ec5?w=800",
    latitude: "37.5683",
    longitude: "126.9984",
    menuItems: [
      { name: "평양냉면", nameEn: "Pyeongyang Cold Buckwheat Noodles", nameZhTw: "平壤冷麵", nameZhCn: "平壤冷面", price: 16000, description: "전통 평양식 냉면" },
      { name: "불고기", nameEn: "Bulgogi", nameZhTw: "烤肉", nameZhCn: "烤肉", price: 37000, description: "한우 불고기 (150g)" },
    ]
  },
  {
    name: "토속촌 삼계탕",
    nameEn: "Tosokchon Samgyetang",
    nameZhTw: "土俗村蔘雞湯",
    nameZhCn: "土俗村参鸡汤",
    category: "korean",
    address: "서울시 종로구 자하문로5길 5",
    addressEn: "5, Jahamun-ro 5-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區紫霞門路5街5",
    addressZhCn: "首尔特别市钟路区紫霞门路5街5",
    phone: "02-737-7444",
    rating: 46,
    reviewCount: 5200,
    price: "moderate",
    hours: "10:00 - 22:00",
    description: "경복궁 근처의 유명한 삼계탕 맛집. 진한 국물과 인삼주가 일품.",
    descriptionEn: "Famous Ginseng Chicken Soup restaurant near Gyeongbokgung. Rich broth and ginseng liquor are excellent.",
    descriptionZhTw: "景福宮附近的著名蔘雞湯美食店。濃郁的湯頭和人蔘酒是一絕。",
    descriptionZhCn: "景福宫附近的著名参鸡汤美食店。浓郁的汤头和人参酒是一绝。",
    image: "https://images.unsplash.com/photo-1594266391456-121d5c5cfc02?w=800",
    latitude: "37.5791",
    longitude: "126.9708",
    menuItems: [
      { name: "토속촌 삼계탕", nameEn: "Tosokchon Samgyetang", nameZhTw: "土俗村蔘雞湯", nameZhCn: "土俗村参鸡汤", price: 20000, description: "대표 메뉴" },
      { name: "오골계 삼계탕", nameEn: "Black Chicken Ginseng Soup", nameZhTw: "烏骨雞蔘雞湯", nameZhCn: "乌骨鸡参鸡汤", price: 25000, description: "검은 닭으로 만든 보양식" },
      { name: "해물파전", nameEn: "Seafood Green Onion Pancake", nameZhTw: "海鮮蔥餅", nameZhCn: "海鲜葱饼", price: 15000, description: "바삭하고 고소한 파전" },
    ]
  },
  {
    name: "광장시장 자매집",
    nameEn: "Jamaejip (Gwangjang Market)",
    nameZhTw: "姐妹家 (廣藏市場)",
    nameZhCn: "姐妹家 (广藏市场)",
    category: "korean",
    address: "서울시 종로구 종로 200-4",
    addressEn: "200-4, Jong-ro, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區鐘路200-4",
    addressZhCn: "首尔特别市钟路区钟路200-4",
    phone: "02-2274-8344",
    rating: 45,
    reviewCount: 1200,
    price: "cheap",
    hours: "09:00 - 22:00",
    description: "광장시장의 명물 육회 맛집. 신선한 육회와 산낙지가 유명합니다.",
    descriptionEn: "Famous Beef Tartare spot in Gwangjang Market. Fresh beef tartare and live octopus are famous.",
    descriptionZhTw: "廣藏市場的名產肉膾美食店。以新鮮的肉膾和活章魚聞名。",
    descriptionZhCn: "广藏市场的名产肉脍美食店。以新鲜的肉脍和活章鱼闻名。",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    latitude: "37.5700",
    longitude: "126.9995",
    menuItems: [
      { name: "육회", nameEn: "Beef Tartare", nameZhTw: "生拌牛肉", nameZhCn: "生拌牛肉", price: 19000, description: "신선한 육회 한 접시" },
      { name: "육회탕탕이", nameEn: "Beef Tartare and Live Octopus", nameZhTw: "肉膾活章魚", nameZhCn: "肉脍活章鱼", price: 32000, description: "육회와 산낙지의 조화" },
      { name: "육회덮밥", nameEn: "Beef Tartare Bibimbap", nameZhTw: "生拌牛肉拌飯", nameZhCn: "生拌牛肉拌饭", price: 9000, description: "든든한 한 끼 식사" },
    ]
  },
  {
    name: "북촌손만두",
    nameEn: "Bukchon Son Mandu",
    nameZhTw: "北村手工餃子",
    nameZhCn: "北村手工饺子",
    category: "korean",
    address: "서울시 종로구 인사동길 42-5",
    addressEn: "42-5, Insadong-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區仁寺洞街42-5",
    addressZhCn: "首尔特别市钟路区仁寺洞街42-5",
    phone: "02-732-1238",
    rating: 44,
    reviewCount: 890,
    price: "cheap",
    hours: "11:00 - 20:00",
    description: "인사동 골목에 위치한 커다란 튀김만두가 유명한 곳.",
    descriptionEn: "Located in Insadong alley, famous for huge fried dumplings.",
    descriptionZhTw: "位於仁寺洞巷弄內，以巨大的炸餃子聞名。",
    descriptionZhCn: "位于仁寺洞巷弄内，以巨大的炸饺子闻名。",
    image: "https://images.unsplash.com/photo-1582234033100-8488e001c3d1?w=800",
    latitude: "37.5744",
    longitude: "126.9859",
    menuItems: [
      { name: "모둠만두", nameEn: "Assorted Dumplings", nameZhTw: "綜合餃子", nameZhCn: "综合饺子", price: 10000, description: "튀김, 찐, 굴림 만두 세트" },
      { name: "피냉면", nameEn: "Cold Noodles", nameZhTw: "皮冷麵", nameZhCn: "皮冷面", price: 8000, description: "시원한 냉면" },
    ]
  },
  {
    name: "진옥화할매원조닭한마리",
    nameEn: "Jinokhwa Halmae Wonjo Dakhanmari",
    nameZhTw: "陳玉華奶奶元祖一隻雞",
    nameZhCn: "陈玉华奶奶元祖一只鸡",
    category: "korean",
    address: "서울시 종로구 종로40가길 18",
    addressEn: "18, Jongro 40ga-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區鐘路40ga街18",
    addressZhCn: "首尔特别市钟路区钟路40ga街18",
    phone: "02-2275-9666",
    rating: 43,
    reviewCount: 3400,
    price: "moderate",
    hours: "10:30 - 01:00",
    description: "동대문의 전설적인 닭한마리집. 맑고 깊은 국물이 특징.",
    descriptionEn: "Legendary whole chicken soup place in Dongdaemun. Clear and deep broth.",
    descriptionZhTw: "東大門傳說的一隻雞店。湯頭清澈濃郁。",
    descriptionZhCn: "东大门传说的一只鸡店。汤头清澈浓郁。",
    image: "https://images.unsplash.com/photo-1594968864731-526487e0b5fa?w=800",
    latitude: "37.5708",
    longitude: "127.0062",
    menuItems: [
      { name: "닭한마리", nameEn: "Whole Chicken", nameZhTw: "一隻雞", nameZhCn: "一只鸡", price: 28000, description: "2~3인분" },
      { name: "떡사리", nameEn: "Rice Cake Topping", nameZhTw: "年糕", nameZhCn: "年糕", price: 2000, description: "쫄깃한 밀떡" },
      { name: "국수사리", nameEn: "Noodle Topping", nameZhTw: "麵條", nameZhCn: "面条", price: 2000, description: "마무리는 칼국수" },
    ]
  },
  // ... INSERT OTHER CATEGORIES HERE ...
  // 2. CAFE (6 restaurants)
  {
    name: "어니언 안국",
    nameEn: "Onion Anguk",
    nameZhTw: "Onion 安國",
    nameZhCn: "Onion 安国",
    category: "cafe",
    address: "서울시 종로구 계동길 5",
    addressEn: "5, Gyedong-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區桂洞街5",
    addressZhCn: "首尔特别市钟路区桂洞街5",
    phone: "070-7543-2123",
    rating: 46,
    reviewCount: 5400,
    price: "moderate",
    hours: "07:00 - 22:00",
    description: "한옥을 개조한 베이커리 카페. 팡도르가 유명함.",
    descriptionEn: "Bakery cafe in a renovated Hanok. Famous for Pandoro.",
    descriptionZhTw: "韓屋改建的烘焙咖啡廳。Pandoro很有名。",
    descriptionZhCn: "韩屋改建的烘焙咖啡厅。Pandoro很有名。",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800",
    latitude: "37.5793",
    longitude: "126.9864",
    menuItems: [
      { name: "팡도르", nameEn: "Pandoro", nameZhTw: "黃金麵包", nameZhCn: "黄金面包", price: 5000, description: "슈가파우더가 듬뿍 뿌려진 빵" },
      { name: "아메리카노", nameEn: "Americano", nameZhTw: "美式咖啡", nameZhCn: "美式咖啡", price: 5000, description: "고소한 원두" },
    ]
  },
  {
    name: "블루보틀 삼청",
    nameEn: "Blue Bottle Coffee Samcheong",
    nameZhTw: "藍瓶咖啡 三清洞",
    nameZhCn: "蓝瓶咖啡 三清洞",
    category: "cafe",
    address: "서울시 종로구 북촌로5길 76",
    addressEn: "76, Bukchon-ro 5-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區北村路5街76",
    addressZhCn: "首尔特别市钟路区北村路5街76",
    phone: "1533-6906",
    rating: 45,
    reviewCount: 3200,
    price: "moderate",
    hours: "09:00 - 20:00",
    description: "북촌 한옥마을의 아름다운 풍경을 즐길 수 있는 카페.",
    descriptionEn: "Cafe with a beautiful view of Bukchon Hanok Village.",
    descriptionZhTw: "可以欣賞北村韓屋村美景的咖啡廳。",
    descriptionZhCn: "可以欣赏北村韩屋村美景的咖啡厅。",
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800",
    latitude: "37.5804",
    longitude: "126.9832",
    menuItems: [
      { name: "뉴올리언스", nameEn: "New Orleans", nameZhTw: "紐奧良冰咖啡", nameZhCn: "新奥尔良冰咖啡", price: 6500, description: "달콤한 아이스 커피" },
    ]
  },
  {
    name: "프리츠 도화",
    nameEn: "Fritz Coffee Company Dowha",
    nameZhTw: "Fritz Coffee Company 桃花",
    nameZhCn: "Fritz Coffee Company 桃花",
    category: "cafe",
    address: "서울시 마포구 새창로2길 17",
    addressEn: "17, Saechang-ro 2-gil, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區新倉路2街17",
    addressZhCn: "首尔特别市麻浦区新仓路2街17",
    phone: "02-3275-2045",
    rating: 47,
    reviewCount: 1800,
    price: "moderate",
    hours: "08:00 - 22:00",
    description: "레트로 감성의 베이커리 카페. 물개가 마스코트.",
    descriptionEn: "Retro vibes bakery cafe. Seal mascot.",
    descriptionZhTw: "復古風格的烘焙咖啡廳。海豹是吉祥物。",
    descriptionZhCn: "复古风格的烘焙咖啡厅。海豹是吉祥物。",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
    latitude: "37.5413",
    longitude: "126.9496",
    menuItems: [
      { name: "크루아상", nameEn: "Croissant", nameZhTw: "可頌", nameZhCn: "可颂", price: 3800, description: "버터 풍미 가득" },
    ]
  },
  {
    name: "런던 베이글 뮤지엄",
    nameEn: "London Bagel Museum",
    nameZhTw: "倫敦貝果博物館",
    nameZhCn: "伦敦贝果博物馆",
    category: "cafe",
    address: "서울시 종로구 북촌로4길 20",
    addressEn: "20, Bukchon-ro 4-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區北村路4街20",
    addressZhCn: "首尔特别市钟路区北村路4街20",
    phone: "02-742-9652",
    rating: 46,
    reviewCount: 8900,
    price: "moderate",
    hours: "08:00 - 18:00",
    description: "서울에서 가장 핫한 베이글 맛집. 웨이팅 필수.",
    descriptionEn: "Hottest bagel place in Seoul. Waiting is essential.",
    descriptionZhTw: "首爾最熱門的貝果店。必須排隊。",
    descriptionZhCn: "首尔最热门的贝果店。必须排队。",
    image: "https://images.unsplash.com/photo-1616632007823-c35d90cc52b9?w=800",
    latitude: "37.5792",
    longitude: "126.9855",
    menuItems: [
      { name: "포테이토 치즈 베이글", nameEn: "Potato Cheese Bagel", nameZhTw: "馬鈴薯起司貝果", nameZhCn: "土豆芝士贝果", price: 5500, description: "베스트셀러" },
    ]
  },
  {
    name: "카페 노티드 청담",
    nameEn: "Cafe Knotted Cheongdam",
    nameZhTw: "Cafe Knotted 清潭",
    nameZhCn: "Cafe Knotted 清潭",
    category: "cafe",
    address: "서울시 강남구 도산대로53길 15",
    addressEn: "15, Dosan-daero 53-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區島山大路53街15",
    addressZhCn: "首尔特别市江南区岛山大路53街15",
    phone: "070-8860-9377",
    rating: 45,
    reviewCount: 4500,
    price: "moderate",
    hours: "09:00 - 21:00",
    description: "귀여운 스마일 로고와 크림 도넛이 유명한 곳.",
    descriptionEn: "Famous for cute smile logo and cream donuts.",
    descriptionZhTw: "以可愛的笑臉標誌和鮮奶油甜甜圈聞名。",
    descriptionZhCn: "以可爱的笑脸标志和鲜奶油甜甜圈闻名。",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800",
    latitude: "37.5244",
    longitude: "127.0387",
    menuItems: [
      { name: "우유 생크림 도넛", nameEn: "Milk Cream Donut", nameZhTw: "牛奶鮮奶油甜甜圈", nameZhCn: "牛奶鲜奶油甜甜圈", price: 3500, description: "시그니처 메뉴" },
    ]
  },
  // 3. STREET FOOD (6 restaurants)
  {
    name: "남도분식 서촌",
    nameEn: "Namdo Bunsik Seochon",
    nameZhTw: "南道小吃 西村",
    nameZhCn: "南道小吃 西村",
    category: "streetFood",
    address: "서울시 종로구 옥인2길 2",
    addressEn: "2, Okin 2-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區玉仁2街2",
    addressZhCn: "首尔特别市钟路区玉仁2街2",
    phone: "02-723-7775",
    rating: 44,
    reviewCount: 1500,
    price: "cheap",
    hours: "11:30 - 21:00",
    description: "이영자 맛집으로 유명한 상추튀김 분식점.",
    descriptionEn: "Famous snack bar for lettuce-wrapped fried food.",
    descriptionZhTw: "以生菜包炸物聞名的小吃店。",
    descriptionZhCn: "以生菜包炸物闻名的小吃店。",
    image: "https://images.unsplash.com/photo-1623227866882-c005c20775d7?w=800",
    latitude: "37.5800",
    longitude: "126.9690",
    menuItems: [
      { name: "상추튀김", nameEn: "Lettuce Wrap Fries", nameZhTw: "生菜炸物", nameZhCn: "生菜炸物", price: 9000, description: "전라도 별미" },
    ]
  },
  {
    name: "바르다김선생",
    nameEn: "Bardakimseonsaeng",
    nameZhTw: "正直的金先生",
    nameZhCn: "正直的金先生",
    category: "streetFood",
    address: "서울시 중구 명동길 43",
    addressEn: "43, Myeongdong-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區明洞街43",
    addressZhCn: "首尔特别市中区明洞街43",
    phone: "02-1234-9999",
    rating: 43,
    reviewCount: 800,
    price: "cheap",
    hours: "10:00 - 22:00",
    description: "건강한 재료를 사용하는 프리미엄 김밥.",
    descriptionEn: "Premium Gimbap using healthy ingredients.",
    descriptionZhTw: "使用健康食材的優質紫菜包飯。",
    descriptionZhCn: "使用健康食材的优质紫菜包饭。",
    image: "https://images.unsplash.com/photo-1583096114844-065dc64bc2a5?w=800",
    latitude: "37.5640",
    longitude: "126.9840",
    menuItems: [
      { name: "바른김밥", nameEn: "Barun Gimbap", nameZhTw: "正直紫菜包飯", nameZhCn: "正直紫菜包饭", price: 4500, description: "기본에 충실한 맛" },
    ]
  },
  {
    name: "엽기떡볶이 동대문본점",
    nameEn: "Yupdduk Dongdaemun",
    nameZhTw: "獵奇辣炒年糕 東大門",
    nameZhCn: "猎奇辣炒年糕 东大门",
    category: "streetFood",
    address: "서울시 중구 다산로 28길 23",
    addressEn: "23, Dasan-ro 28-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區茶山路28街23",
    addressZhCn: "首尔特别市中区茶山路28街23",
    phone: "02-2236-8592",
    rating: 45,
    reviewCount: 3000,
    price: "cheap",
    hours: "11:00 - 23:00",
    description: "엄청나게 매운 맛으로 유명한 떡볶이.",
    descriptionEn: "Tteokbokki famous for its extremely spicy taste.",
    descriptionZhTw: "以超辣口味聞名的辣炒年糕。",
    descriptionZhCn: "以超辣口味闻名的辣炒年糕。",
    image: "https://images.unsplash.com/photo-1563897539633-2680c2975217?w=800",
    latitude: "37.5670",
    longitude: "127.0170",
    menuItems: [
      { name: "엽기떡볶이", nameEn: "Yupdduk", nameZhTw: "獵奇辣炒年糕", nameZhCn: "猎奇辣炒年糕", price: 14000, description: "3-4인분" },
    ]
  },
  {
    name: "명랑핫도그",
    nameEn: "Myungrang Hotdog",
    nameZhTw: "明朗熱狗",
    nameZhCn: "明朗热狗",
    category: "streetFood",
    address: "서울시 마포구 어울마당로 112",
    addressEn: "112, Eoulmadang-ro, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區如意廣場路112",
    addressZhCn: "首尔特别市麻浦区如意广场路112",
    phone: "02-333-1234",
    rating: 46,
    reviewCount: 900,
    price: "cheap",
    hours: "11:00 - 23:00",
    description: "바삭하고 치즈가 듬뿍 들어간 쌀 핫도그.",
    descriptionEn: "Crispy rice hotdog filled with cheese.",
    descriptionZhTw: "酥脆且充滿起司的米熱狗。",
    descriptionZhCn: "酥脆且充满芝士的米热狗。",
    image: "https://images.unsplash.com/photo-1627260586976-52bd6228303f?w=800",
    latitude: "37.5560",
    longitude: "126.9240",
    menuItems: [
      { name: "모짜렐라 핫도그", nameEn: "Mozzarella Hotdog", nameZhTw: "莫札瑞拉起司熱狗", nameZhCn: "莫扎里拉芝士热狗", price: 2500, description: "치즈 반 소세지 반" },
    ]
  },
  {
    name: "석관동떡볶이",
    nameEn: "Seokgwandong Topokki",
    nameZhTw: "石串洞辣炒年糕",
    nameZhCn: "石串洞辣炒年糕",
    category: "streetFood",
    address: "서울시 마포구 홍익로3길 29",
    addressEn: "29, Hongik-ro 3-gil, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區弘益路3街29",
    addressZhCn: "首尔特别市麻浦区弘益路3街29",
    phone: "02-322-9999",
    rating: 42,
    reviewCount: 600,
    price: "cheap",
    hours: "12:00 - 22:00",
    description: "기름떡볶이가 맛있는 분식집.",
    descriptionEn: "Snack bar with delicious Oil Tteokbokki.",
    descriptionZhTw: "油炒年糕很好吃的小吃店。",
    descriptionZhCn: "油炒年糕很好吃的小吃店。",
    image: "https://images.unsplash.com/photo-1626804475297-411dbe6314f3?w=800",
    latitude: "37.5550",
    longitude: "126.9230",
    menuItems: [
      { name: "기름떡볶이", nameEn: "Oil Tteokbokki", nameZhTw: "油炒年糕", nameZhCn: "油炒年糕", price: 5000, description: "고소하고 매콤한 맛" },
    ]
  },
  {
    name: "에그드랍",
    nameEn: "Egg Drop",
    nameZhTw: "Egg Drop",
    nameZhCn: "Egg Drop",
    category: "streetFood",
    address: "서울시 마포구 홍익로 15",
    addressEn: "15, Hongik-ro, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區弘益路15",
    addressZhCn: "首尔特别市麻浦区弘益路15",
    phone: "02-332-1111",
    rating: 44,
    reviewCount: 1500,
    price: "cheap",
    hours: "08:00 - 21:00",
    description: "프리미엄 에그 샌드위치.",
    descriptionEn: "Premium Egg Sandwich.",
    descriptionZhTw: "高級雞蛋三明治。",
    descriptionZhCn: "高级鸡蛋三明治。",
    image: "https://images.unsplash.com/photo-1525351484163-7529414395d8?w=800",
    latitude: "37.5540",
    longitude: "126.9210",
    menuItems: [
      { name: "미스터 에그", nameEn: "Mr. Egg", nameZhTw: "Mr. Egg", nameZhCn: "Mr. Egg", price: 3900, description: "스크램블 에그 샌드위치" },
    ]
  },
  // ... INSERT OTHER CATEGORIES HERE ...
  // 4. BBQ (6 restaurants)
  {
    name: "왕비집 명동본점",
    nameEn: "Wangbijib Myeongdong",
    nameZhTw: "王妃家 明洞本店",
    nameZhCn: "王妃家 明洞本店",
    category: "bbq",
    address: "서울시 중구 명동8가길 26",
    addressEn: "26, Myeongdong 8ga-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區明洞8ga街26",
    addressZhCn: "首尔特别市中区明洞8ga街26",
    phone: "02-3789-1945",
    rating: 47,
    reviewCount: 2300,
    price: "expensive",
    hours: "11:30 - 22:00",
    description: "외국인에게 인기 있는 프리미엄 갈비 맛집.",
    descriptionEn: "Premium Galbi restaurant popular among foreigners.",
    descriptionZhTw: "受外國人歡迎的高級排骨美食店。",
    descriptionZhCn: "受外国人欢迎的高级排骨美食店。",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800",
    latitude: "37.5615",
    longitude: "126.9855",
    menuItems: [
      { name: "양념갈비 정식", nameEn: "Marinated Galbi Set", nameZhTw: "調味排骨定食", nameZhCn: "调味排骨定食", price: 23000, description: "점심 특선" },
      { name: "한우 등심", nameEn: "Hanwoo Sirloin", nameZhTw: "韓牛里脊", nameZhCn: "韩牛里脊", price: 45000, description: "최상급 한우" },
    ]
  },
  {
    name: "금돼지식당",
    nameEn: "Gold Pig Restaurant",
    nameZhTw: "金豬食堂",
    nameZhCn: "金猪食堂",
    category: "bbq",
    address: "서울시 중구 다산로 149",
    addressEn: "149, Dasan-ro, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區茶山路149",
    addressZhCn: "首尔特别市中区茶山路149",
    phone: "0507-1307-8750",
    rating: 48,
    reviewCount: 4500,
    price: "moderate",
    hours: "11:30 - 23:00",
    description: "미쉐린 가이드에 선정된 삼겹살 맛집.",
    descriptionEn: "Pork belly restaurant selected by Michelin Guide.",
    descriptionZhTw: "入選米其林指南的五花肉美食店。",
    descriptionZhCn: "入选米其林指南的五花肉美食店。",
    image: "https://images.unsplash.com/photo-1594911772125-07fc7a2d8d1f?w=800",
    latitude: "37.5567",
    longitude: "127.0101",
    menuItems: [
      { name: "본삼겹", nameEn: "Bone-in Pork Belly", nameZhTw: "帶骨五花肉", nameZhCn: "带骨五花肉", price: 19000, description: "갈비뼈가 붙은 삼겹살" },
    ]
  },
  {
    name: "숙달돼지 종각점",
    nameEn: "Sookdal Pork Jonggak",
    nameZhTw: "熟達豬肉 鐘閣店",
    nameZhCn: "熟达猪肉 钟阁店",
    category: "bbq",
    address: "서울시 종로구 종로8길 15",
    addressEn: "15, Jong-ro 8-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區鐘路8街15",
    addressZhCn: "首尔特别市钟路区钟路8街15",
    phone: "02-737-5201",
    rating: 46,
    reviewCount: 1200,
    price: "moderate",
    hours: "11:30 - 23:00",
    description: "습식 숙성 삼겹살 전문점. 부드러운 육질이 특징.",
    descriptionEn: "Wet-aged pork belly specialty store. Characterized by tender meat quality.",
    descriptionZhTw: "濕式熟成五花肉專賣店。以肉質鮮嫩為特徵。",
    descriptionZhCn: "湿式熟成五花肉专卖店。以肉质鲜嫩为特征。",
    image: "https://images.unsplash.com/photo-1603366445787-09714680cbf1?w=800",
    latitude: "37.5695",
    longitude: "126.9835",
    menuItems: [
      { name: "숙성 통삼겹", nameEn: "Aged Pork Belly", nameZhTw: "熟成厚切五花肉", nameZhCn: "熟成厚切五花肉", price: 16000, description: "최적의 숙성" },
    ]
  },
  {
    name: "하남돼지집 강남점",
    nameEn: "Hanam Pig House Gangnam",
    nameZhTw: "河南豬肉家 江南店",
    nameZhCn: "河南猪肉家 江南店",
    category: "bbq",
    address: "서울시 강남구 강남대로96길 15",
    addressEn: "15, Gangnam-daero 96-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區江南大路96街15",
    addressZhCn: "首尔特别市江南区江南大路96街15",
    phone: "02-538-9292",
    rating: 45,
    reviewCount: 1500,
    price: "moderate",
    hours: "16:00 - 24:00",
    description: "초벌구이해서 나오는 돼지고기 맛집. 직원이 구워줍니다.",
    descriptionEn: "Pork restaurant serving pre-grilled meat. Staff grills for you.",
    descriptionZhTw: "提供初烤豬肉的美食店。職員會幫忙烤。",
    descriptionZhCn: "提供初烤猪肉的美食店。职员会帮忙烤。",
    image: "https://images.unsplash.com/photo-1627802830863-715ce92518e3?w=800",
    latitude: "37.4998",
    longitude: "127.0275",
    menuItems: [
      { name: "모듬한판", nameEn: "Assorted Platter", nameZhTw: "綜合拼盤", nameZhCn: "综合拼盘", price: 46000, description: "삼겹살, 목살, 갈비" },
    ]
  },
  {
    name: "새마을식당 논현점",
    nameEn: "Saemaul Sikdang Nonhyeon",
    nameZhTw: "新村食堂 論峴店",
    nameZhCn: "新村食堂 论岘店",
    category: "bbq",
    address: "서울시 강남구 학동로2길 45",
    addressEn: "45, Hakdong-ro 2-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區鶴洞路2街45",
    addressZhCn: "首尔特别市江南区鹤洞路2街45",
    phone: "02-544-3284",
    rating: 44,
    reviewCount: 2100,
    price: "cheap",
    hours: "24 hours",
    description: "백종원의 유명한 열탄불고기와 7분돼지김치.",
    descriptionEn: "Baek Jong-won's famous Yeoltan Bulgogi and 7-minute Pork Kimchi.",
    descriptionZhTw: "白種元的著名熱炭烤肉和7分鐘豬肉泡菜。",
    descriptionZhCn: "白种元的著名热炭烤肉和7分钟猪肉泡菜。",
    image: "https://images.unsplash.com/photo-1596796929656-5b3287340ec5?w=800",
    latitude: "37.5090",
    longitude: "127.0230",
    menuItems: [
      { name: "열탄불고기", nameEn: "Yeoltan Bulgogi", nameZhTw: "熱炭烤肉", nameZhCn: "热炭烤肉", price: 10900, description: "매콤한 불맛" },
      { name: "7분돼지김치", nameEn: "7-min Pork Kimchi", nameZhTw: "7分鐘豬肉泡菜", nameZhCn: "7分钟猪肉泡菜", price: 8000, description: "밥도둑 찌개" },
    ]
  },
  {
    name: "투뿔등심 광화문점",
    nameEn: "Two Plus Deungsim Gwanghwamun",
    nameZhTw: "Two Plus 里脊 光化門店",
    nameZhCn: "Two Plus 里脊 光化门店",
    category: "bbq",
    address: "서울시 중구 세종대로 136",
    addressEn: "136, Sejong-daero, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區世宗大路136",
    addressZhCn: "首尔特别市中区世宗大路136",
    phone: "02-3789-7577",
    rating: 46,
    reviewCount: 900,
    price: "expensive",
    hours: "11:30 - 22:00",
    description: "최상급 1++ 한우 등심 전문점. 콜키지 프리.",
    descriptionEn: "Top quality 1++ Hanwoo Sirloin specialty. Corkage free.",
    descriptionZhTw: "頂級1++韓牛里脊專賣店。免開瓶費。",
    descriptionZhCn: "顶级1++韩牛里脊专卖店。免开瓶费。",
    image: "https://images.unsplash.com/photo-1626202168019-d97151246c59?w=800",
    latitude: "37.5680",
    longitude: "126.9770",
    menuItems: [
      { name: "투뿔숙성등심", nameEn: "Aged 1++ Sirloin", nameZhTw: "熟成1++里脊", nameZhCn: "熟成1++里脊", price: 47000, description: "입에서 녹는 맛" },
    ]
  },
  // 5. SEAFOOD (6 restaurants)
  {
    name: "노량진 수산시장 황제식당",
    nameEn: "Noryangjin Fish Market Emperor",
    nameZhTw: "鷺梁津水產市場 皇帝食堂",
    nameZhCn: "鹭梁津水产市场 皇帝食堂",
    category: "seafood",
    address: "서울시 동작구 노들로 674",
    addressEn: "674, Nodeul-ro, Dongjak-gu, Seoul",
    addressZhTw: "首爾特別市銅雀區鷺得路674",
    addressZhCn: "首尔特别市铜雀区鹭得路674",
    phone: "02-2254-8888",
    rating: 44,
    reviewCount: 890,
    price: "moderate",
    hours: "00:00 - 24:00",
    description: "싱싱한 해산물을 바로 회떠먹는 즐거움.",
    descriptionEn: "Joy of eating fresh sashimi right away.",
    descriptionZhTw: "享受現切新鮮海鮮的樂趣。",
    descriptionZhCn: "享受现切新鲜海鲜的乐趣。",
    image: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800",
    latitude: "37.5130",
    longitude: "126.9420",
    menuItems: [
      { name: "모듬회", nameEn: "Assorted Sashimi", nameZhTw: "綜合生魚片", nameZhCn: "综合生鱼片", price: 50000, description: "계절별 제철 생선" },
      { name: "킹크랩 찜", nameEn: "Steamed King Crab", nameZhTw: "蒸帝王蟹", nameZhCn: "蒸帝王蟹", price: 90000, description: "싯가" },
    ]
  },
  {
    name: "배키욘방",
    nameEn: "Baeky Yonbang",
    nameZhTw: "Baeky Yonbang",
    nameZhCn: "Baeky Yonbang",
    category: "seafood",
    address: "서울시 송파구 올림픽로32길 22-23",
    addressEn: "22-23, Olympic-ro 32-gil, Songpa-gu, Seoul",
    addressZhTw: "首爾特別市松坡區奧林匹克路32街22-23",
    addressZhCn: "首尔特别市松坡区奥林匹克路32街22-23",
    phone: "02-422-9999",
    rating: 46,
    reviewCount: 1500,
    price: "moderate",
    hours: "11:30 - 21:00",
    description: "일본식 덮밥과 우동 맛집. 연어덮밥이 일품.",
    descriptionEn: "Japanese Donburi and Udon. Salmon Donburi is excellent.",
    descriptionZhTw: "日式蓋飯和烏龍麵美食店。鮭魚蓋飯是一絕。",
    descriptionZhCn: "日式盖饭和乌龙面美食店。鲑鱼盖饭是一绝。",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800",
    latitude: "37.5140",
    longitude: "127.1080",
    menuItems: [
      { name: "사케동", nameEn: "Salmon Rice Bowl", nameZhTw: "鮭魚蓋飯", nameZhCn: "鲑鱼盖饭", price: 16000, description: "신선한 연어" },
    ]
  },
  {
    name: "오복수산 도산",
    nameEn: "Obok Susan Dosan",
    nameZhTw: "五福水產 島山",
    nameZhCn: "五福水产 岛山",
    category: "seafood",
    address: "서울시 강남구 도산대로53길 14",
    addressEn: "14, Dosan-daero 53-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區島山大路53街14",
    addressZhCn: "首尔特别市江南区岛山大路53街14",
    phone: "02-545-9966",
    rating: 47,
    reviewCount: 2200,
    price: "expensive",
    hours: "11:30 - 21:30",
    description: "신선한 우니와 해산물이 가득한 카이센동 전문점.",
    descriptionEn: "Kaisendon specialty store full of fresh Uni and seafood.",
    descriptionZhTw: "充滿新鮮海膽和海鮮的海鮮蓋飯專賣店。",
    descriptionZhCn: "充满新鲜海胆和海鲜的海鲜盖饭专卖店。",
    image: "https://images.unsplash.com/photo-1606850780554-b55ea2ce9850?w=800",
    latitude: "37.5240",
    longitude: "127.0380",
    menuItems: [
      { name: "우니동", nameEn: "Sea Urchin Rice Bowl", nameZhTw: "海膽蓋飯", nameZhCn: "海胆盖饭", price: 45000, description: "최상급 우니" },
      { name: "카이센동", nameEn: "Seafood Rice Bowl", nameZhTw: "海鮮蓋飯", nameZhCn: "海鲜盖饭", price: 25000, description: "다양한 해산물" },
    ]
  },
  {
    name: "마포나룻집",
    nameEn: "Mapo Narutjib",
    nameZhTw: "麻浦渡口家",
    nameZhCn: "麻浦渡口家",
    category: "seafood",
    address: "서울시 마포구 어울마당로 76-1",
    addressEn: "76-1, Eoulmadang-ro, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區如意廣場路76-1",
    addressZhCn: "首尔特别市麻浦区如意广场路76-1",
    phone: "02-337-5515",
    rating: 43,
    reviewCount: 1100,
    price: "moderate",
    hours: "11:00 - 24:00",
    description: "꽃게장과 새우장이 맛있는 홍대 맛집.",
    descriptionEn: "Hongdae restaurant with delicious Soy Sauce Crab and Shrimp.",
    descriptionZhTw: "醬蟹和醬蝦很好吃的弘大美食店。",
    descriptionZhCn: "酱蟹和酱虾很好吃的弘大美食店。",
    image: "https://images.unsplash.com/photo-1599021453965-0c7f7690f042?w=800",
    latitude: "37.5520",
    longitude: "126.9240",
    menuItems: [
      { name: "간장게장", nameEn: "Soy Sauce Crab", nameZhTw: "醬蟹", nameZhCn: "酱蟹", price: 35000, description: "밥도둑" },
    ]
  },
  {
    name: "진원조보신닭한마리",
    nameEn: "Jinwonjo Dakhanmari",
    nameZhTw: "陳元祖補身一隻雞",
    nameZhCn: "陈元祖补身一只鸡",
    category: "seafood",
    address: "서울시 종로구 종로40가길 3",
    addressEn: "3, Jongro 40ga-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區鐘路40ga街3",
    addressZhCn: "首尔特别市钟路区钟路40ga街3",
    phone: "02-1234-5555",
    rating: 42,
    reviewCount: 500,
    price: "moderate",
    hours: "10:00 - 23:00",
    description: "얼큰한 국물의 닭볶음탕과 해물.",
    descriptionEn: "Spicy Braised Chicken and Seafood.",
    descriptionZhTw: "香辣雞肉鍋和海鮮。",
    descriptionZhCn: "香辣鸡肉锅和海鲜。",
    image: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800",
    latitude: "37.5700",
    longitude: "127.0060",
    menuItems: [
      { name: "낙지볶음", nameEn: "Stir-fried Octopus", nameZhTw: "辣炒章魚", nameZhCn: "辣炒章鱼", price: 30000, description: "매콤한 술안주" },
    ]
  },
  {
    name: "무교동유정낙지 본점",
    nameEn: "Mugyodong Yujeong Octopus",
    nameZhTw: "武橋洞有情章魚",
    nameZhCn: "武桥洞有情章鱼",
    category: "seafood",
    address: "서울시 중구 세종대로21길 22",
    addressEn: "22, Sejong-daero 21-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區世宗大路21街22",
    addressZhCn: "首尔特别市中区世宗大路21街22",
    phone: "02-736-5244",
    rating: 45,
    reviewCount: 1200,
    price: "moderate",
    hours: "11:00 - 22:00",
    description: "화끈하게 매운 낙지볶음의 원조.",
    descriptionEn: "Origin of spicy stir-fried octopus.",
    descriptionZhTw: "火辣辣的辣炒章魚始祖。",
    descriptionZhCn: "火辣辣的辣炒章鱼始祖。",
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=800",
    latitude: "37.5685",
    longitude: "126.9780",
    menuItems: [
      { name: "낙지볶음", nameEn: "Stir-fried Octopus", nameZhTw: "辣炒章魚", nameZhCn: "辣炒章鱼", price: 29000, description: "스트레스 풀리는 매운맛" },
    ]
  },
  // 6. DESSERT (6 restaurants)
  {
    name: "설빙 홍대입구역점",
    nameEn: "Sulbing Hongdae",
    nameZhTw: "雪冰 弘大",
    nameZhCn: "雪冰 弘大",
    category: "dessert",
    address: "서울시 마포구 홍익로 6길 15",
    addressEn: "15, Hongik-ro 6-gil, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區弘益路6街15",
    addressZhCn: "首尔特别市麻浦区弘益路6街15",
    phone: "02-323-9999",
    rating: 45,
    reviewCount: 3000,
    price: "moderate",
    hours: "11:00 - 23:00",
    description: "한국식 눈꽃빙수 전문점. 인절미 빙수가 유명함.",
    descriptionEn: "Korean snowflake shaved ice specialty. Injeolmi Bingsu is famous.",
    descriptionZhTw: "韓式雪花冰專賣店。年糕雪冰很有名。",
    descriptionZhCn: "韩式雪花冰专卖店。年糕雪冰很有名。",
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
    latitude: "37.5560",
    longitude: "126.9230",
    menuItems: [
      { name: "인절미설빙", nameEn: "Injeolmi Sulbing", nameZhTw: "年糕雪冰", nameZhCn: "年糕雪冰", price: 8900, description: "고소한 콩가루 빙수" },
      { name: "애플망고치즈설빙", nameEn: "Apple Mango Cheese Sulbing", nameZhTw: "蘋果芒果起司雪冰", nameZhCn: "苹果芒果芝士雪冰", price: 12900, description: "달콤한 망고 빙수" },
    ]
  },
  {
    name: "오설록 티하우스 북촌점",
    nameEn: "Osulloc Tea House Bukchon",
    nameZhTw: "Osulloc Tea House 北村",
    nameZhCn: "Osulloc Tea House 北村",
    category: "dessert",
    address: "서울시 종로구 북촌로 45",
    addressEn: "45, Bukchon-ro, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區北村路45",
    addressZhCn: "首尔特别市钟路区北村路45",
    phone: "02-739-9293",
    rating: 47,
    reviewCount: 1500,
    price: "moderate",
    hours: "11:00 - 21:00",
    description: "제주 녹차로 만든 다양한 디저트와 차를 즐길 수 있는 곳.",
    descriptionEn: "Enjoy various desserts and tea made with Jeju green tea.",
    descriptionZhTw: "可以享用濟州綠茶製作的各種甜點和茶的地方。",
    descriptionZhCn: "可以享用济州绿茶制作的各种甜点和茶的地方。",
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcf8?w=800",
    latitude: "37.5810",
    longitude: "126.9830",
    menuItems: [
      { name: "녹차 오프레도", nameEn: "Green Tea O Fredo", nameZhTw: "綠茶O Fredo", nameZhCn: "绿茶O Fredo", price: 7500, description: "녹차 쉐이크와 아이스크림" },
      { name: "녹차 롤케익", nameEn: "Green Tea Roll Cake", nameZhTw: "綠茶瑞士捲", nameZhCn: "绿茶瑞士卷", price: 6000, description: "부드러운 크림" },
    ]
  },
  {
    name: "카페 마마스 광화문점",
    nameEn: "Cafe Mamas Gwanghwamun",
    nameZhTw: "Cafe Mamas 光化門",
    nameZhCn: "Cafe Mamas 光化门",
    category: "dessert",
    address: "서울시 종로구 종로1길 50",
    addressEn: "50, Jong-ro 1-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區鐘路1街50",
    addressZhCn: "首尔特别市钟路区钟路1街50",
    phone: "02-736-1212",
    rating: 44,
    reviewCount: 2200,
    price: "moderate",
    hours: "08:00 - 21:30",
    description: "리코타 치즈 샐러드와 파니니가 맛있는 브런치 카페.",
    descriptionEn: "Brunch cafe with delicious Ricotta Cheese Salad and Panini.",
    descriptionZhTw: "瑞可塔起司沙拉和帕尼尼很好吃的早午餐咖啡廳。",
    descriptionZhCn: "瑞可塔芝士沙拉和帕尼尼很好吃的早午餐咖啡厅。",
    image: "https://images.unsplash.com/photo-1579306194872-64d3b7bac4c2?w=800",
    latitude: "37.5740",
    longitude: "126.9790",
    menuItems: [
      { name: "리코타 치즈 샐러드", nameEn: "Ricotta Cheese Salad", nameZhTw: "瑞可塔起司沙拉", nameZhCn: "瑞可塔芝士沙拉", price: 14800, description: "신선한 샐러드" },
    ]
  },
  {
    name: "빌리엔젤 강남역점",
    nameEn: "Billy Angel Gangnam",
    nameZhTw: "Billy Angel 江南",
    nameZhCn: "Billy Angel 江南",
    category: "dessert",
    address: "서울시 강남구 테헤란로1길 48",
    addressEn: "48, Teheran-ro 1-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區德黑蘭路1街48",
    addressZhCn: "首尔特别市江南区德黑兰路1街48",
    phone: "02-553-1111",
    rating: 43,
    reviewCount: 900,
    price: "moderate",
    hours: "11:00 - 23:00",
    description: "다양한 종류의 케이크를 맛볼 수 있는 디저트 카페.",
    descriptionEn: "Dessert cafe where you can taste various types of cakes.",
    descriptionZhTw: "可以品嚐各種蛋糕的甜點咖啡廳。",
    descriptionZhCn: "可以品尝各种蛋糕的甜点咖啡厅。",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    latitude: "37.4980",
    longitude: "127.0280",
    menuItems: [
      { name: "당근 케이크", nameEn: "Carrot Cake", nameZhTw: "胡蘿蔔蛋糕", nameZhCn: "胡萝卜蛋糕", price: 7800, description: "시그니처 케이크" },
    ]
  },
  {
    name: "도레도레 신사점",
    nameEn: "Dore Dore Sinsa",
    nameZhTw: "Dore Dore 新沙",
    nameZhCn: "Dore Dore 新沙",
    category: "dessert",
    address: "서울시 강남구 도산대로15길 40",
    addressEn: "40, Dosan-daero 15-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區島山大路15街40",
    addressZhCn: "首尔特别市江南区岛山大路15街40",
    phone: "02-540-4553",
    rating: 44,
    reviewCount: 1100,
    price: "moderate",
    hours: "11:00 - 22:00",
    description: "무지개 케이크로 유명한 가로수길 카페.",
    descriptionEn: "Garosugil cafe famous for Rainbow Cake.",
    descriptionZhTw: "以彩虹蛋糕聞名的林蔭道咖啡廳。",
    descriptionZhCn: "以彩虹蛋糕闻名的林荫道咖啡厅。",
    image: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=800",
    latitude: "37.5200",
    longitude: "127.0230",
    menuItems: [
      { name: "무지개 케이크", nameEn: "Rainbow Cake", nameZhTw: "彩虹蛋糕", nameZhCn: "彩虹蛋糕", price: 9500, description: "알록달록한 케이크" },
    ]
  },
  {
    name: "라인프렌즈 카페 홍대",
    nameEn: "Line Friends Cafe Hongdae",
    nameZhTw: "Line Friends Cafe 弘大",
    nameZhCn: "Line Friends Cafe 弘大",
    category: "dessert",
    address: "서울시 마포구 양화로 141",
    addressEn: "141, Yanghwa-ro, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區楊花路141",
    addressZhCn: "首尔特别市麻浦区杨花路141",
    phone: "02-322-9631",
    rating: 45,
    reviewCount: 3000,
    price: "moderate",
    hours: "11:00 - 22:00",
    description: "귀여운 브라운과 코니 캐릭터 디저트.",
    descriptionEn: "Cute Brown and Cony character desserts.",
    descriptionZhTw: "可愛的熊大和兔兔角色甜點。",
    descriptionZhCn: "可爱的熊大和兔兔角色甜点。",
    image: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=800",
    latitude: "37.5560",
    longitude: "126.9230",
    menuItems: [
      { name: "브라운 초코 무스", nameEn: "Brown Choco Mousse", nameZhTw: "熊大巧克力慕斯", nameZhCn: "熊大巧克力慕斯", price: 6500, description: "진한 초콜릿 맛" },
    ]
  },
  // 7. NOODLES (6 restaurants)
  {
    name: "오레노라멘 합정본점",
    nameEn: "Oreno Ramen Hapjeong",
    nameZhTw: "Oreno拉麵 合井",
    nameZhCn: "Oreno拉面 合井",
    category: "noodles",
    address: "서울시 마포구 독막로6길 14",
    addressEn: "14, Dokmak-ro 6-gil, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區獨幕路6街14",
    addressZhCn: "首尔特别市麻浦区独幕路6街14",
    phone: "02-322-3539",
    rating: 47,
    reviewCount: 3500,
    price: "cheap",
    hours: "11:30 - 21:00",
    description: "미쉐린 가이드 빕 구르망 라멘 맛집. 진한 닭 육수.",
    descriptionEn: "Michelin Bib Gourmand Ramen. Rich chicken broth.",
    descriptionZhTw: "米其林必比登推薦拉麵。濃郁的雞湯。",
    descriptionZhCn: "米其林必比登推荐拉面。浓郁的鸡汤。",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    latitude: "37.5480",
    longitude: "126.9170",
    menuItems: [
      { name: "토리 빠이탄", nameEn: "Tori Paitan", nameZhTw: "雞白湯拉麵", nameZhCn: "鸡白汤拉面", price: 11000, description: "진하고 고소한 맛" },
      { name: "카라 빠이탄", nameEn: "Kara Paitan", nameZhTw: "辣雞白湯拉麵", nameZhCn: "辣鸡白汤拉面", price: 11000, description: "매콤한 맛" },
    ]
  },
  {
    name: "멘야하나비 잠실",
    nameEn: "Menya Hanabi Jamsil",
    nameZhTw: "Menya Hanabi 蠶室",
    nameZhCn: "Menya Hanabi 蚕室",
    category: "noodles",
    address: "서울시 송파구 백제고분로45길 38",
    addressEn: "38, Baekjegobun-ro 45-gil, Songpa-gu, Seoul",
    addressZhTw: "首爾特別市松坡區百濟古墳路45街38",
    addressZhCn: "首尔特别市松坡区百济古坟路45街38",
    phone: "070-8959-1108",
    rating: 46,
    reviewCount: 2800,
    price: "cheap",
    hours: "11:30 - 21:00",
    description: "마제소바(일본식 비빔면) 원조 맛집.",
    descriptionEn: "Original Mazesoba (Japanese mixed noodles).",
    descriptionZhTw: "日式拌麵元祖美食店。",
    descriptionZhCn: "日式拌面元祖美食店。",
    image: "https://images.unsplash.com/photo-1552611052-33e04de081de?w=800",
    latitude: "37.5120",
    longitude: "127.1120",
    menuItems: [
      { name: "마제소바", nameEn: "Mazesoba", nameZhTw: "日式拌麵", nameZhCn: "日式拌面", price: 11000, description: "감칠맛 폭발" },
    ]
  },
  {
    name: "미분당 신촌점",
    nameEn: "Mibundang Sinchon",
    nameZhTw: "米粉堂 新村",
    nameZhCn: "米粉堂 新村",
    category: "noodles",
    address: "서울시 서대문구 연세로5다길 26",
    addressEn: "26, Yonsei-ro 5da-gil, Seodaemun-gu, Seoul",
    addressZhTw: "首爾特別市西大門區延世路5da街26",
    addressZhCn: "首尔特别市西大门区延世路5da街26",
    phone: "02-3141-0855",
    rating: 46,
    reviewCount: 3000,
    price: "cheap",
    hours: "11:00 - 21:00",
    description: "조용하고 깔끔한 한국식 쌀국수 맛집.",
    descriptionEn: "Quiet and clean Korean-style Pho restaurant.",
    descriptionZhTw: "安靜乾淨的韓式河粉美食店。",
    descriptionZhCn: "安静干净的韩式河粉美食店。",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    latitude: "37.5560",
    longitude: "126.9350",
    menuItems: [
      { name: "차돌박이 쌀국수", nameEn: "Brisket Pho", nameZhTw: "牛胸肉河粉", nameZhCn: "牛胸肉河粉", price: 10000, description: "담백한 국물" },
    ]
  },
  {
    name: "을지면옥",
    nameEn: "Eulji Myeonok",
    nameZhTw: "乙支麵屋",
    nameZhCn: "乙支面屋",
    category: "noodles",
    address: "서울시 중구 충무로14길 2-1",
    addressEn: "2-1, Chungmu-ro 14-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區忠武路14街2-1",
    addressZhCn: "首尔特别市中区忠武路14街2-1",
    phone: "02-2266-7052",
    rating: 45,
    reviewCount: 1800,
    price: "moderate",
    hours: "11:00 - 21:00",
    description: "전통 평양냉면의 명가. 맑은 육수가 특징.",
    descriptionEn: "Famous traditional Pyeongyang Naengmyeon. Clear broth.",
    descriptionZhTw: "傳統平壤冷麵名店。清澈的肉湯。",
    descriptionZhCn: "传统平壤冷面名店。清澈的肉汤。",
    image: "https://images.unsplash.com/photo-1596796929656-5b3287340ec5?w=800",
    latitude: "37.5650",
    longitude: "126.9920",
    menuItems: [
      { name: "냉면", nameEn: "Cold Noodles", nameZhTw: "冷麵", nameZhCn: "冷面", price: 14000, description: "평양식 물냉면" },
    ]
  },
  {
    name: "진미평양냉면",
    nameEn: "Jinmi Pyeongyang Naengmyeon",
    nameZhTw: "真味平壤冷麵",
    nameZhCn: "真味平壤冷面",
    category: "noodles",
    address: "서울시 강남구 학동로 305-3",
    addressEn: "305-3, Hakdong-ro, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區鶴洞路305-3",
    addressZhCn: "首尔特别市江南区鹤洞路305-3",
    phone: "02-515-3469",
    rating: 47,
    reviewCount: 2000,
    price: "moderate",
    hours: "11:00 - 21:30",
    description: "성시경이 추천한 평양냉면 맛집.",
    descriptionEn: "Pyeongyang Naengmyeon recommended by Sung Si-kyung.",
    descriptionZhTw: "成始璄推薦的平壤冷麵美食店。",
    descriptionZhCn: "成始璄推荐的平壤冷面美食店。",
    image: "https://images.unsplash.com/photo-1596796929656-5b3287340ec5?w=800",
    latitude: "37.5160",
    longitude: "127.0360",
    menuItems: [
      { name: "냉면", nameEn: "Cold Noodles", nameZhTw: "冷麵", nameZhCn: "冷面", price: 14000, description: "진한 육향" },
    ]
  },
  {
    name: "깡통만두",
    nameEn: "Kkangtong Mandu",
    nameZhTw: "空罐頭餃子",
    nameZhCn: "空罐头饺子",
    category: "noodles",
    address: "서울시 종로구 북촌로2길 5-6",
    addressEn: "5-6, Bukchon-ro 2-gil, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區北村路2街5-6",
    addressZhCn: "首尔特别市钟路区北村路2街5-6",
    phone: "02-794-4243",
    rating: 46,
    reviewCount: 1500,
    price: "moderate",
    hours: "11:30 - 21:30",
    description: "비빔국수와 만두전골이 유명한 안국역 맛집.",
    descriptionEn: "Famous for Spicy Noodles and Dumpling Hot Pot near Anguk St.",
    descriptionZhTw: "安國站附近的拌麵和餃子火鍋美食店。",
    descriptionZhCn: "安国站附近的拌面和饺子火锅美食店。",
    image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=800",
    latitude: "37.5770",
    longitude: "126.9850",
    menuItems: [
      { name: "비빔국수", nameEn: "Spicy Noodles", nameZhTw: "拌麵", nameZhCn: "拌面", price: 12000, description: "육전이 올라간 국수" },
    ]
  },
  // 8. CHICKEN (6 restaurants)
  {
    name: "교촌치킨 홍대점",
    nameEn: "Kyochon Chicken Hongdae",
    nameZhTw: "橋村炸雞 弘大店",
    nameZhCn: "桥村炸鸡 弘大店",
    category: "chicken",
    address: "서울시 마포구 양화로16길 6",
    addressEn: "6, Yanghwa-ro 16-gil, Mapo-gu, Seoul",
    addressZhTw: "首爾特別市麻浦區楊花路16街6",
    addressZhCn: "首尔特别市麻浦区杨花路16街6",
    phone: "02-338-1300",
    rating: 46,
    reviewCount: 3000,
    price: "moderate",
    hours: "12:00 - 02:00",
    description: "간장 치킨의 원조. 허니콤보가 인기.",
    descriptionEn: "Original Soy Sauce Chicken. Honey Combo is popular.",
    descriptionZhTw: "醬油炸雞元祖。蜂蜜組合很受歡迎。",
    descriptionZhCn: "酱油炸鸡元祖。蜂蜜组合很受欢迎。",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
    latitude: "37.5550",
    longitude: "126.9210",
    menuItems: [
      { name: "허니콤보", nameEn: "Honey Combo", nameZhTw: "蜂蜜組合", nameZhCn: "蜂蜜组合", price: 23000, description: "달콤짭짤한 맛" },
    ]
  },
  {
    name: "BHC 치킨 명동본점",
    nameEn: "BHC Chicken Myeongdong",
    nameZhTw: "BHC炸雞 明洞本店",
    nameZhCn: "BHC炸鸡 明洞本店",
    category: "chicken",
    address: "서울시 중구 명동7길 21",
    addressEn: "21, Myeongdong 7-gil, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區明洞7街21",
    addressZhCn: "首尔特别市中区明洞7街21",
    phone: "02-3789-0990",
    rating: 45,
    reviewCount: 2500,
    price: "moderate",
    hours: "12:00 - 24:00",
    description: "전지현 치킨으로 유명한 뿌링클.",
    descriptionEn: "Famous for 'Prinkle' chicken endorsed by Jun Ji-hyun.",
    descriptionZhTw: "全智賢炸雞，Prinkle很有名。",
    descriptionZhCn: "全智贤炸鸡，Prinkle很有名。",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800",
    latitude: "37.5640",
    longitude: "126.9830",
    menuItems: [
      { name: "뿌링클", nameEn: "Prinkle", nameZhTw: "Prinkle", nameZhCn: "Prinkle", price: 21000, description: "치즈 가루 치킨" },
    ]
  },
  {
    name: "BBQ 치킨 종로관철점",
    nameEn: "BBQ Chicken Jongno",
    nameZhTw: "BBQ炸雞 鐘路",
    nameZhCn: "BBQ炸鸡 钟路",
    category: "chicken",
    address: "서울시 종로구 청계천로 81",
    addressEn: "81, Cheonggyecheon-ro, Jongno-gu, Seoul",
    addressZhTw: "首爾特別市鐘路區清溪川路81",
    addressZhCn: "首尔特别市钟路区清溪川路81",
    phone: "02-725-9282",
    rating: 45,
    reviewCount: 1800,
    price: "moderate",
    hours: "11:00 - 24:00",
    description: "황금올리브 치킨이 가장 유명한 곳.",
    descriptionEn: "Most famous for Golden Olive Chicken.",
    descriptionZhTw: "黃金橄欖油炸雞最有名的地方。",
    descriptionZhCn: "黄金橄榄油炸鸡最有名的地方。",
    image: "https://images.unsplash.com/photo-1569691899455-59756b12a806?w=800",
    latitude: "37.5690",
    longitude: "126.9860",
    menuItems: [
      { name: "황금올리브치킨", nameEn: "Golden Olive Chicken", nameZhTw: "黃金橄欖油炸雞", nameZhCn: "黄金橄榄油炸鸡", price: 22000, description: "바삭함의 끝판왕" },
    ]
  },
  {
    name: "굽네치킨 서대문역점",
    nameEn: "Goobne Chicken Seodaemun",
    nameZhTw: "Goobne炸雞 西大門",
    nameZhCn: "Goobne炸鸡 西大门",
    category: "chicken",
    address: "서울시 중구 통일로 132",
    addressEn: "132, Tongil-ro, Jung-gu, Seoul",
    addressZhTw: "首爾特別市中區統一路132",
    addressZhCn: "首尔特别市中区统—路132",
    phone: "02-392-9294",
    rating: 44,
    reviewCount: 1200,
    price: "moderate",
    hours: "12:00 - 24:00",
    description: "오븐에 구워 기름기를 뺀 건강한 치킨.",
    descriptionEn: "Healthy oven-roasted chicken with less oil.",
    descriptionZhTw: "烤箱烘烤去油的健康炸雞。",
    descriptionZhCn: "烤箱烘烤去油的健康炸鸡。",
    image: "https://images.unsplash.com/photo-1566379517596-f6048d0865c6?w=800",
    latitude: "37.5660",
    longitude: "126.9670",
    menuItems: [
      { name: "고추바사삭", nameEn: "Pepper Crispy", nameZhTw: "辣椒脆皮", nameZhCn: "辣椒脆皮", price: 21000, description: "매콤하고 바삭한 맛" },
    ]
  },
  {
    name: "칸부치킨 삼성점",
    nameEn: "Kkanbu Chicken Samseong",
    nameZhTw: "Kkanbu炸雞 三成",
    nameZhCn: "Kkanbu炸鸡 三成",
    category: "chicken",
    address: "서울시 강남구 삼성로96길 3",
    addressEn: "3, Samseong-ro 96-gil, Gangnam-gu, Seoul",
    addressZhTw: "首爾特別市江南區三成路96街3",
    addressZhCn: "首尔特别市江南区三成路96街3",
    phone: "02-565-9292",
    rating: 46,
    reviewCount: 1500,
    price: "moderate",
    hours: "16:00 - 02:00",
    description: "깔끔하고 모던한 분위기의 치킨집.",
    descriptionEn: "Clean and modern atmosphere chicken restaurant.",
    descriptionZhTw: "乾淨現代氛圍的炸雞店。",
    descriptionZhCn: "干净现代氛围的炸鸡店。",
    image: "https://images.unsplash.com/photo-1627662244907-7ae15c67d643?w=800",
    latitude: "37.5090",
    longitude: "127.0560",
    menuItems: [
      { name: "크리스피 치킨", nameEn: "Crispy Chicken", nameZhTw: "脆皮炸雞", nameZhCn: "脆皮炸鸡", price: 20000, description: "기본에 충실한 맛" },
    ]
  },
  {
    name: "누룽지통닭구이",
    nameEn: "Nurungji Tongdak",
    nameZhTw: "鍋巴烤雞",
    nameZhCn: "锅巴烤鸡",
    category: "chicken",
    address: "서울시 용산구 한강대로62나길 16",
    addressEn: "16, Hangang-daero 62na-gil, Yongsan-gu, Seoul",
    addressZhTw: "首爾特別市龍山區漢江大路62na街16",
    addressZhCn: "首尔特别市龙山区汉江大路62na街16",
    phone: "02-798-3333",
    rating: 45,
    reviewCount: 2000,
    price: "moderate",
    hours: "16:00 - 24:00",
    description: "참나무 장작으로 구운 통닭과 누룽지.",
    descriptionEn: "Oak wood roasted chicken and scorched rice.",
    descriptionZhTw: "橡木柴火烤雞和鍋巴。",
    descriptionZhCn: "橡木柴火烤鸡和锅巴。",
    image: "https://images.unsplash.com/photo-1598103138688-662584d4197e?w=800",
    latitude: "37.5320",
    longitude: "126.9690",
    menuItems: [
      { name: "누룽지 통닭", nameEn: "Nurungji Chicken", nameZhTw: "鍋巴炸雞", nameZhCn: "锅巴炸鸡", price: 20000, description: "구수한 누룽지" },
    ]
  },
];

async function seed() {
  try {
    console.log("🌱 Seeding database...");

    // Clear existing data (optional, be careful in production)
    // await sql`TRUNCATE TABLE restaurants, menu_items CASCADE`;

    for (const r of restaurants) {
      console.log(`Adding ${r.name}...`);

      const [restaurant] = await sql`
        INSERT INTO restaurants (
          name, name_en, name_zh_tw, name_zh_cn,
          category, address, address_en, address_zh_tw, address_zh_cn,
          phone, rating, review_count, price, hours,
          description, description_en, description_zh_tw, description_zh_cn,
          image, latitude, longitude
        ) VALUES (
          ${r.name}, ${r.nameEn}, ${r.nameZhTw}, ${r.nameZhCn},
          ${r.category}, ${r.address}, ${r.addressEn}, ${r.addressZhTw}, ${r.addressZhCn},
          ${r.phone}, ${r.rating}, ${r.reviewCount}, ${r.price}, ${r.hours},
          ${r.description}, ${r.descriptionEn}, ${r.descriptionZhTw}, ${r.descriptionZhCn},
          ${r.image}, ${r.latitude}, ${r.longitude}
        )
        RETURNING id
      `;

      if (r.menuItems && r.menuItems.length > 0) {
        for (const m of r.menuItems) {
          await sql`
            INSERT INTO menu_items (
              restaurant_id, name, name_en, name_zh_tw, name_zh_cn,
              price, description
            ) VALUES (
              ${restaurant.id}, ${m.name}, ${m.nameEn}, ${m.nameZhTw}, ${m.nameZhCn},
              ${m.price}, ${m.description}
            )
          `;
        }
      }
    }

    console.log("🎉 Seeding completed!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

seed();
